hibernate.connection.driver_class=org.sqlite.JDBC
hibernate.connection.url=jdbc:sqlite:plugins/ServerDatabaseController/database.db
hibernate.connection.username=
hibernate.connection.password=


hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

hibernate.hbm2ddl.auto=update